export const MOVIE_LOADED = 'MOVIE_LOADED';
export const PLAYLIST_LOADED = 'PLAYLIST_LOADED';
export const MOVIE_COMPLETED = 'MOVIE_COMPLETED';
export const MOVIE_LIST_LOADED = 'MOVIE_LIST_LOADED';
export const RECOMMENDED_MOVIES_LOADED = 'RECOMMENDED_MOVIES_LOADED';
